// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using SkincareProductSalesSystem.RazorWebApp.Models;

namespace SkincareProductSalesSystem.Repositories.Models;

public partial class Product
{
    public string ProductId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public decimal Price { get; set; }

    public string CategoryId { get; set; }

    public string BrandId { get; set; }

    public int? StockQuantity { get; set; }

    public string ImageUrl { get; set; }

    public string Ingredients { get; set; }

    public bool? IsActive { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual Brand Brand { get; set; }
    public virtual Category Category { get; set; }
}