// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SkincareProductSalesSystem.RazorWebApp.Models;

public class SkinTest
{
    public string QuestionId { get; set; }

    public string Question { get; set; }

    public int? QuestionOrder { get; set; }

    public bool? IsActive { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual List<SkinTestOption> SkinTestOptions { get; set; } = new List<SkinTestOption>();
}

public class SkinTestOption
{
    public string OptionId { get; set; }

    public string OptionText { get; set; }

    public string SkinTypeId { get; set; }
}