// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SkincareProductSalesSystem.RazorWebApp.Models;

public partial class SkinTest
{
    public string TestId { get; set; }

    public string Question { get; set; }

    public string OptionA { get; set; }

    public string OptionB { get; set; }

    public string OptionC { get; set; }

    public string OptionD { get; set; }

    public string CorrectSkinTypeId { get; set; }

    public int? QuestionOrder { get; set; }

    public bool? IsActive { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual SkinType CorrectSkinType { get; set; }
}