// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SkincareProductSalesSystem.Repositories.Models;

public partial class BlogPost
{
    public string PostId { get; set; }

    public string Title { get; set; }

    public string Content { get; set; }

    public string AuthorId { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public string BlogCategory { get; set; }

    public string ImageUrl { get; set; }

    public string Tags { get; set; }

    public int? ViewCount { get; set; }

    public virtual User Author { get; set; }
}