// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SkincareProductSalesSystem.Repositories.Models;

public partial class CustomerAddress
{
    public string CustomerAddressId { get; set; }

    public string ReceiverPhoneNumber { get; set; }

    public string Province { get; set; }

    public string District { get; set; }

    public string Ward { get; set; }

    public string Street { get; set; }

    public string AddressType { get; set; }

    public bool? DefaultAddress { get; set; }

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();
}