// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SkincareProductSalesSystem.Repositories.Models;

public partial class Payment
{
    public string PaymentId { get; set; }

    public string Code { get; set; }

    public string PaymentMethodId { get; set; }

    public string OrderId { get; set; }

    public string PaymentStatus { get; set; }

    public decimal PaymentAmount { get; set; }

    public string TransactionId { get; set; }

    public DateTime? PaymentDate { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual Order Order { get; set; }

    public virtual PaymentMethod PaymentMethod { get; set; }
}