// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SkincareProductSalesSystem.Repositories.Models;

public partial class PaymentMethod
{
    public string PaymentMethodId { get; set; }

    public string Name { get; set; }

    public string ImgUrl { get; set; }

    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();
}