// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SkincareProductSalesSystem.Repositories.Models;

public partial class PromotionUsage
{
    public string UsageId { get; set; }

    public string PromotionId { get; set; }

    public string OrderId { get; set; }

    public decimal DiscountAmount { get; set; }

    public DateTime? UsedAt { get; set; }

    public bool? IsValid { get; set; }

    public string Notes { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual Order Order { get; set; }

    public virtual Promotion Promotion { get; set; }
}