// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace SkincareProductSalesSystem.Repositories.Models;

public partial class Promotion
{
	[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	public string PromotionId { get; set; }

    public string Code { get; set; }

    public string Name { get; set; }

    public decimal DiscountAmount { get; set; }

    public decimal? MinimumPurchase { get; set; }

    public DateTime StartDate { get; set; }

    public DateTime EndDate { get; set; }

    public int? UsageLimit { get; set; }

    public bool? IsActive { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual ICollection<PromotionUsage> PromotionUsages { get; set; } = new List<PromotionUsage>();
}