// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SkincareProductSalesSystem.Repositories.Models;

public partial class SkinType
{
    public string SkinTypeId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public string Characteristics { get; set; }

    public string RecommendedIngredients { get; set; }

    public string AvoidIngredients { get; set; }

    public string CareInstructions { get; set; }

    public bool? IsActive { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual ICollection<CustomerProfile> CustomerProfiles { get; set; } = new List<CustomerProfile>();

    public virtual ICollection<SkinCareRoutine> SkinCareRoutines { get; set; } = new List<SkinCareRoutine>();

    public virtual ICollection<SkinTestOption> SkinTestOptions { get; set; } = new List<SkinTestOption>();

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();
}