// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SkincareProductSalesSystem.Repositories.Models;

public partial class SkinTestQuestion
{
    public string QuestionId { get; set; }

    public string Question { get; set; }

    public int? QuestionOrder { get; set; }

    public bool? IsActive { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual ICollection<SkinTestOption> SkinTestOptions { get; set; } = new List<SkinTestOption>();
}