// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SkincareProductSalesSystem.Repositories.Models;

public partial class SkinTestOption
{
    public string OptionId { get; set; }

    public string QuestionId { get; set; }

    public string OptionText { get; set; }

    public string SkinTypeId { get; set; }

    public virtual SkinTestQuestion Question { get; set; }

    public virtual SkinType SkinType { get; set; }
}